[package]
name = "rest_api_image"
version = "0.1.0"
authors = ["Mikhail Hasso <mihasso@protonmail.com>"]
edition = "2018"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
